### PR TITLE
Reduce bacon gif size

### PR DESCRIPTION
**Pull request by niroyb**
From 10 frames to 3.
Optimized gif.
From 1MB down to 180KB.

### CODE REVIEW

**Comment by christoga** [comment]
👍👍👍

**Comment by nabijaczleweli** [comment]
:-1:

**Comment by niroyb** [comment]
It makes the tests run faster by having less frames to convert and @JuanPotato was concerned about the file size initially.

**Comment by nabijaczleweli** [comment]
Nothing is a good justification for lessening the amount of bacon

**Comment by nabijaczleweli** [comment]
I'm crying

**Comment by JuanPotato** [comment]
@nabijaczleweli Don't worry I have a way to cheer you up.

1. Go eat bacon
2. Be happy

**Comment by nabijaczleweli** [comment]
Cheers

**Pull request merged**
