### PR TITLE
Add licence entry on file readme and install command on Fedora Linux

### PR DESCRIPTION
**Pull request by berroteran**

### CODE REVIEW

**Comment by JuanPotato** [comment]
I mean, if we're putting installation instructions why not put in other installations like pip or [arch aur](https://aur.archlinux.org/packages/legofy-git/)?

**Comment by berroteran** [comment]
@JuanPotato  
> If you think dont is good idea then I close my PR.

Best,

**Comment by JuanPotato** [comment]
You know, the standard way a pull request works is that you make a change, and the repo owner can request reasonable additions or changes. Requesting changes doesn't mean your pull request is bad.

**Comment by berroteran** [comment]
> You know, the standard way a pull request works is that you make a change, and the repo owner can request reasonable additions or changes. Requesting changes doesn't mean your pull request is bad.

@JuanPotato I know no problem,  All about chill. 
Just close so, because someone report my account also. 

so, its O.k.

**Pull request closed without merging**
