### PR TITLE
Master

### PR DESCRIPTION
**Pull request by wentz-s**
Added a —hd option that outputs a higher resolution version of the picture.

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Why not add an option to manually specify `sizeScale`?

**Comment by wentz-s** [comment]
thank you @nabijaczleweli for the suggestion. I just implemented it.

**Comment by JuanPotato** [comment]
I hope to add this soon, been lazy

**Comment by JuanPotato** [comment]
I am bad at merges, added this in 25f5c88dd84ce8b3405d306063c6fe46aa52a585 using --bricks

**Pull request closed without merging**
