### PR TITLE
Use correct plural of lego

### PR DESCRIPTION
**Pull request by aperson**
I'm sorry I had to be that guy.

### CODE REVIEW

**Comment by JuanPotato** [comment]
You are that guy, but I don't think "created in lego" sounds right, maybe "made with lego pieces" or "built with lego"

**Comment by rjw57** [comment]
:+1: for "built out of lego" or similar.

**Comment by martinbjeldbak** [comment]
Continuing being that guy, we might as well do it right: LEGO should be typeset in all capitals.

**Comment by johnnonolan** [comment]
:+1:

**Comment by nabijaczleweli** [comment]
:+1:

**Comment by JuanPotato** [comment]
done did, just differently

**Pull request closed without merging**
