### PR TITLE
updated copyright disclaimer

### PR DESCRIPTION
**Pull request by rduan8**
All rights reserved

### CODE REVIEW

**Comment by JuanPotato** [comment]
What does this do? Not exactly familiar with licences and such, but the MIT license doesn't have this included in the template.

**Comment by HugoGiraudel** [comment]
You might need something like this because you are using the LEGO brand. I am not entirely sure how it works that being said, and I don’t think “All rights reserved” is enough in any case.

**Comment by JuanPotato** [comment]
@HugoGiraudel Yeah, I know nothing about licenses and stuff like this, so I would need to look it up.

**Comment by JuanPotato** [comment]
sure, why not

**Pull request merged**
