### PR TITLE
new bricks

### PR DESCRIPTION
**Pull request by zahradtj**
Created 1x2 brick and 2x1 brick

### CODE REVIEW

**Comment by zahradtj** [comment]
Some work on #47

**Comment by todrobbins** [comment]
:+1:

**Comment by JuanPotato** [comment]
What I was aiming for was a brand new lego brick, not based on the already made one, please see #47 I know how to make the new bricks, it would just seem better to make a new version. I won't be merging this though as I have a higher quality lego brick that I will be creating a 2x1 and 1x2 brick. The current ones you made have a very slight light/dark border in the middle, just doesn't seem right.

**Comment by HugoGiraudel** [comment]
@zahradtj Out of curiosity, where did you get those images from? Also, do they exist in SVG?

**Pull request closed without merging**
