### PR TITLE
enhance the Legofy to only use Lego colors

### PR DESCRIPTION
**Pull request by WendellLiu**
i just add a function "getNearestColor" in legofy

BTW, tests/nearestColor.py was made for me to test the function and you don't have to merge this on main project

### CODE REVIEW

**Comment by ewjoachim** [comment]
I think you'd have quite better result if you implemented getNearestColor with HSV or HSL (which can be done easily with [colorsys](https://docs.python.org/2/library/colorsys.html) from the standard lib (#BatteriesIncluded). Then it might be interesting to multiply either component with a scalar constant to change their relative importance.

Worth noting that [Wikipedia](https://en.wikipedia.org/wiki/Color_difference) has an article on color difference which point to rather using L*a*b and [Python-colormap](https://github.com/gtaylor/python-colormath) has [specific functions](http://python-colormath.readthedocs.org/en/latest/delta_e.html#example) for computing color distances.

Main point is : computing distance by doing an euclidean distance over RGB coordinates does not result with the visually closest color.

**Comment by christoga** [comment]
I think you better modified your colors again and change it with material design color
The list of the hex is [here](https://www.google.com/design/spec/style/color.html#color-color-palette)
And because the color of the site is hex,
Try to use HEX to RGB Converter, check it [here](http://hex.colorrrs.com/)

**Comment by WendellLiu** [comment]
thanks all!
I will fix my problem as soon as possible

**Comment by WendellLiu** [comment]
@christoga 
I'm confused why i should change the colors with material design color.
what's advantage in this way?

thanks for your suggestion

**Comment by ewjoachim** [comment]
I think @christoga wanted to say that Material Design offers a palette of colors that should **look** better.  That could be interesting as an option, if we could choose our palette, but given the goal of this pull request, using the official LEGO colors should be the main feature we add ... we can still add the option to chose a better palette in a subsequent PR based on what this one offers, though.

**Comment by JuanPotato** [comment]
I'm still trying to find a fix for something before I merge this, and I'll probably be implementing the nearest color in a different way. Great stuff though

**Comment by JuanPotato** [comment]
better merge has been merged

**Pull request closed without merging**
