### PR TITLE
Add more tests, drop 3.2 not supported by click

### PR DESCRIPTION
**Pull request by niroyb**

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Looks good for me.

(also +1000 for that bacon)

**Comment by niroyb** [comment]
Thanks!
Any idea when this is going to be merged or what other work has to be done?

**Comment by JuanPotato** [comment]
I'm just wondering what we can do about 3.2, and I am trying to to include big files like gifs in the github so that it can clone quicker

**Comment by niroyb** [comment]
You could remove the dependency to click or add 3.2 support to click. The
reason they dropped 3.2 is PEP 0414.
This should be in a different pull request since it is unrelated.

The gif is 1.3 Mb, there is only one for testing purposes and it is only
downloaded once when cloning.
Cloning quicker is not a valid argument : It takes travis 0.7 seconds
<https://travis-ci.org/niroyb/Legofy/jobs/89420944>to clone with the gif...

**Comment by JuanPotato** [comment]
With my internet speed, It takes an awkward amount of time to clone the 5mb that is the git now (I need to remove some deleted files), so it is a valid argument, but its not terrible. I'll merge, might replace the gif with a smaller one later

**Comment by niroyb** [comment]
Thanks, a shallow git clone is faster since it does not download the history. Again, it only has to be done once. Replacing with a smaller one is also a good idea.

**Pull request merged**
