### PR TITLE
Refactor and improvements

### PR DESCRIPTION
**Pull request by niroyb**
Fail early on Windows if there is no MAGICK_HOME env var.
Fix bug where gif would use frames of a previous run if the previous run
was canceled.
Fix failure exit return codes.

### CODE REVIEW

**Comment by JuanPotato** [comment]
I only have one comment, why do you have most variables snake_case but then left plenty in camelCase?

**Comment by JuanPotato** [comment]
Now if only I can go through all this without getting confused again, then I will merge it, Great work! I need to go to sleep

**Comment by JuanPotato** [comment]
Just found out btw, using call("convert", shell=True) makes python use ImageMagick convert, adding this soon or you can

**Comment by niroyb** [comment]
Thanks, I'd recommend *not *using shell=True.
It opens the code to many vulnerabilities.
<http://stackoverflow.com/questions/3172470/actual-meaning-of-shell-true-in-subprocess>Even
the doc recommends against it.
<https://docs.python.org/2/library/subprocess.html#using-the-subprocess-module>

Nick

**Comment by JuanPotato** [comment]
I understand, I wonder if there is another way to bypass the windows convert or find the ImageMagick dir more reliably.

**Pull request merged**
