### PR TITLE
Use the output parameter

### LINKED ISSUE #15: "output" argument not used
@click.argument('output', default=None, required=False)
    def main(brick, image, output):
        # [..]

.. but then it's not passed to anything (or used).

### PR DESCRIPTION
**Pull request by Brobin**
#### Changes

 - Pass the output parameter to the main method
 - Check if it is set, otherwise prepend `lego_`
 - Remove file extension manipulation so the user can specify it
 - Add unit tests :shipit: 

Closes #15

### CODE REVIEW

**Comment by JuanPotato** [comment]
Only one problem with this, jpg encoding doesn't work on every system. without installing a few extras at times, in my experience, so setting it as png was my workaround. When someone uses --output new_image.jpg it is not certain that it will work correctly.

**Comment by JuanPotato** [comment]
well I attempted to merge this while fixing conflicts and failed...

**Comment by Brobin** [comment]
No problem, it looks like you have a lot of people helping out

**Comment by JuanPotato** [comment]
Yeah, this is the first time I made a program that got popular, so I don't have much experience with github anyway. It's been really nice seeing the program develop with other people's ideas.

**Comment by Brobin** [comment]
Yeah, it's pretty fun to work on projects with people from all over!

**Comment by JuanPotato** [comment]
Indeed, I wonder what my next project will be.

**Pull request closed without merging**
