### PR TITLE
Removing unused parameter output as per #15

### PR DESCRIPTION
**Pull request by marcelocure**

### CODE REVIEW

**Comment by marcelocure** [comment]
is it a pre requisite to work with python >=3.2?

**Comment by JuanPotato** [comment]
yes

**Comment by marcelocure** [comment]
I made a confusion, I fixed two bugs on the same PR, just consider the #15
I'll raise a new PR for the bug #30 later
Can you check this before?

**Comment by JuanPotato** [comment]
I will be going through all the PRs after I finish up what I've been working on. Do what you want, I'm busy at the moment.

**Comment by JuanPotato** [comment]
Fixed with recent commit

**Pull request closed without merging**
